// Contenido inicial: sesiones reales del máster (Excel v2).
// Se usa solo la primera vez que la base de datos está vacía.
export const SEED_SESIONES = [
  {
    "id": "s1",
    "bloque": "1.Product Thinking",
    "tipo": "Institucional / calendario",
    "titulo": "Jornada de Bienvenida (I)",
    "profesor": "",
    "comunicada": "2026-09-24",
    "confirmada": "2026-09-24",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s2",
    "bloque": "1.Product Thinking",
    "tipo": "Institucional / calendario",
    "titulo": "Jornada de Bienvenida (II)",
    "profesor": "",
    "comunicada": "2026-09-25",
    "confirmada": "2026-09-25",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s3",
    "bloque": "1.Product Thinking",
    "tipo": "Sesión de contenido",
    "titulo": "Design thinking y nuevas metodologías (diseñar y liderar en un contexto con IA)",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "2026-09-28",
    "confirmada": "2026-09-28",
    "objetivos": "Principal: Iniciar en los conceptos de diseño de producto, identificando qué fases pueden apoyarse en IA y cuáles requieren intervención humana.\n- Comprender qué es Design Thinking, sus beneficios, limitaciones y principales aplicaciones.\n- Conocer otras metodologías de diseño y distinguir sus diferencias, usos y condiciones de aplicación.",
    "ejemplo": "- Investigar y comparar al menos dos metodologías mediante criterios comunes: finalidad, fases, contexto, ventajas y limitaciones.\n- Justificar el uso o no uso de IA en las fases de una metodología elegida para un caso concreto.",
    "indice": "- Introducción: qué es diseñar producto (y qué no)\n- Design Thinking: origen, doble diamante, beneficios y limitaciones\n- Críticas actuales al Design Thinking y qué aprender de ellas\n- Otras metodologías: Lean UX, Design Sprint, diseño centrado en datos\n- Criterios para comparar y elegir metodología: finalidad, fases, contexto, ventajas, límites.\n- La IA en el proceso de diseño: fases que puede apoyar, acelerar o automatizar vs. fases que exigen intervención humana\n- [Práctica] Comparativa de dos metodologías con criterios comunes\n- [Práctica] Mapa fase a fase: uso o no uso de IA justificado para un caso concreto."
  },
  {
    "id": "s4",
    "bloque": "1.Product Thinking",
    "tipo": "Sesión de contenido",
    "titulo": "Product mindset: problema, valor, usuario",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "2026-09-29",
    "confirmada": "2026-09-29",
    "objetivos": "Principal: Identificar un problema de producto que conecte necesidad del usuario, contexto de uso y oportunidad de valor para el negocio, sin anticipar prematuramente una solución.\n- Comprender la diferencia entre problema, necesidad, deseo, solución y propuesta de valor.\n- Identificar necesidades subyacentes y entender el concepto de iteración y mejora continua.",
    "ejemplo": "- Reformular un brief orientado a solución como problem statement.\n- Elaborar una propuesta de valor inicial y explicitar las hipótesis que todavía deben validarse.",
    "indice": ""
  },
  {
    "id": "s5",
    "bloque": "1.Product Thinking",
    "tipo": "Sesión de contenido",
    "titulo": "Fundamentos de diseño y Leyes de UX",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "2026-09-30",
    "confirmada": "2026-09-30",
    "objetivos": "Principal: Evaluar y mejorar una interfaz justificando las decisiones mediante principios de percepción, jerarquía visual, usabilidad y comportamiento humano.\n- Conocer leyes y principios fundamentales de UX y diseño visual.\n- Reconocer cómo jerarquía, contraste, proximidad, consistencia y carga cognitiva afectan a la comprensión y al uso.",
    "ejemplo": "- Realizar una crítica de una interfaz.\n- Priorizar problemas y proponer mejoras vinculando cada decisión con el principio que la sustenta.",
    "indice": ""
  },
  {
    "id": "s6",
    "bloque": "1.Product Thinking",
    "tipo": "Sesión de contenido",
    "titulo": "Básicos de Figma (I)",
    "profesor": "Paula Girela González",
    "comunicada": "2026-10-01",
    "confirmada": "2026-10-01",
    "objetivos": "Principal: Construir una primera interfaz estructurada y editable aplicando una organización de archivo que facilite la colaboración y la iteración.\n- Conocer la lógica de frames, estilos y componentes básicos.\n- Comprender los fundamentos de auto layout y del trabajo colaborativo en Figma.",
    "ejemplo": "- Crear una pantalla sencilla con frames, auto layout y componentes básicos.\n- Compartir el archivo con una estructura y nomenclatura comprensibles para otra persona.",
    "indice": ""
  },
  {
    "id": "s7",
    "bloque": "1.Product Thinking",
    "tipo": "Sesión de contenido",
    "titulo": "Modelo de Calidad Total (I)",
    "profesor": "Josep Martínez",
    "comunicada": "2026-10-05",
    "confirmada": "2026-10-05",
    "objetivos": "Principal: Analizar un problema de producto desde el Modelo de Calidad Total para formularlo de manera sistémica, basada en hechos y compatible con las necesidades de los cinco componentes.\n- Comprender los cinco componentes y reconocer cómo una decisión centrada únicamente en el usuario puede generar problemas de ejecución, viabilidad o sostenibilidad.\n- Identificar los paradigmas y supuestos desde los que se interpreta un brief, diferenciando hechos, opiniones, síntomas y causas.\n- Aplicar verdades universales como contrastación, hechos, no palabras y todo efecto tiene una causa para cuestionar el problema antes de diseñar.",
    "ejemplo": "- Investigar y comparar al menos dos metodologías mediante criterios comunes: finalidad, fases, contexto, ventajas y limitaciones.\n- Justificar el uso o no uso de IA en las fases de una metodología elegida para un caso concreto.",
    "indice": "- Misión y Visión\n- Verdades Universales\n- Paradigmas"
  },
  {
    "id": "s8",
    "bloque": "1.Product Thinking",
    "tipo": "Sesión de contenido",
    "titulo": "Básicos de Figma (II)",
    "profesor": "Paula Girela González",
    "comunicada": "2026-10-06",
    "confirmada": "2026-10-06",
    "objetivos": "Principal: Construir componentes reutilizables y adaptables que mantengan consistencia sin limitar innecesariamente la evolución de la interfaz.\n- Comprender variantes, propiedades, estados y auto layout anidado.\n- Diferenciar instancia de componente",
    "ejemplo": "- Crear un componente con variantes y estados relevantes.\n- Utilizarlo en varios contextos y comprobar que conserva coherencia y capacidad de edición.",
    "indice": ""
  },
  {
    "id": "s9",
    "bloque": "1.Product Thinking",
    "tipo": "Sesión de contenido",
    "titulo": "Propuesta de valor y MVP",
    "profesor": "Jonás Suarez",
    "comunicada": "2026-10-07",
    "confirmada": "2026-10-07",
    "objetivos": "Principal: Traducir la propuesta de valor de un producto en hipótesis contrastables y diseñar el MVP como experimento mínimo para validarlas antes de invertir en desarrollo.\n- Formalizar la propuesta de valor inicial con una herramienta estructurada (p. ej. Value Proposition Canvas) y evaluar su encaje problema–solución.\n- Comprender qué es y qué no es un MVP, diferenciándolo de una versión reducida, incompleta o “cutre” del producto.",
    "ejemplo": "- Elaborar la propuesta de valor de un caso y derivar de ella las hipótesis críticas (problema, solución, valor) que deben validarse primero.\n- Diseñar el MVP mínimo y el experimento más barato para contrastar esas hipótesis, definiendo métrica y criterio de éxito, y justificar la decisión de pivotar o perseverar.",
    "indice": ""
  },
  {
    "id": "s10",
    "bloque": "1.Product Thinking",
    "tipo": "Skills",
    "titulo": "CONÓCETE: AUTOCONOCIMIENTO",
    "profesor": "Juan Portillo",
    "comunicada": "2026-10-08",
    "confirmada": "2026-10-08",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s11",
    "bloque": "2.Estado actual del Diseño de Producto Digital y AI-Native Thinking",
    "tipo": "Sesión de contenido",
    "titulo": "Fundamentos de IA",
    "profesor": "Manu Lorenzo",
    "comunicada": "2026-10-13",
    "confirmada": "2026-10-13",
    "objetivos": "Principal: Comprender los fundamentos de la inteligencia artificial generativa para utilizar herramientas conversacionales de forma básica, consciente y segura.\n- Diferenciar IA, machine learning, deep learning e IA generativa, diferenciando sus capacidades y limitaciones\n- Tener nociones de cómo funcionan los modelos y por qué sus respuestas son probabilísticas y no deterministas.\n- Comprender la función del prompt, el contexto, la memoria y las instrucciones personalizadas.\n- Reconocer riesgos básicos relacionados con alucinaciones, sesgos, privacidad, protección de datos y uso poco transparente.",
    "ejemplo": "- Comparar la respuesta de dos herramientas de IA ante una misma tarea sencilla, identificando diferencias, errores y limitaciones.",
    "indice": ""
  },
  {
    "id": "s12",
    "bloque": "2.Estado actual del Diseño de Producto Digital y AI-Native Thinking",
    "tipo": "Sesión de contenido",
    "titulo": "Definición y evolución del diseño de producto digital e impacto de la IA",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "2026-10-14",
    "confirmada": "2026-10-14",
    "objetivos": "Principal: Entender cómo cambia el rol del diseñador de producto y decidir qué capacidades humanas deben reforzarse en un contexto de automatización.\n- Comprender la evolución de UX/UI hacia diseño de producto y trabajo multidisciplinar.\n- Identificar tareas automatizables, apoyadas con IA y las no delegables.",
    "ejemplo": "- Mapear del rol actual con responsabilidades, decisiones y relaciones con otras disciplinas. (Apoyándose en Linkedin)\n- Argumentar qué competencias diferencian a un diseñador de alto valor.",
    "indice": ""
  },
  {
    "id": "s13",
    "bloque": "2.Estado actual del Diseño de Producto Digital y AI-Native Thinking",
    "tipo": "Empleabilidad",
    "titulo": "Taller CV + Linkedin + Speech",
    "profesor": "",
    "comunicada": "2026-10-15",
    "confirmada": "2026-10-15",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s14",
    "bloque": "2.Estado actual del Diseño de Producto Digital y AI-Native Thinking",
    "tipo": "Sesión de contenido",
    "titulo": "Básicos de Figma (III): Ejercicio Figma AI",
    "profesor": "Paula Girela González",
    "comunicada": "2026-10-15",
    "confirmada": "2026-10-15",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s15",
    "bloque": "2.Estado actual del Diseño de Producto Digital y AI-Native Thinking",
    "tipo": "Sesión de contenido",
    "titulo": "AI-native mindset y herramientas base (Lovable, Figma y Claude) (I)",
    "profesor": "Germán Enguix",
    "comunicada": "2026-10-19",
    "confirmada": "2026-10-19",
    "objetivos": "Principal: Construir una primera solución con herramientas AI-native y valorar si responde al problema, no solo si funciona técnicamente.\n- Conocer las posibilidades básicas de Lovable, Figma y Claude dentro de un flujo de diseño. (Hacer referencia aDEsign Thinking que vieron el tema anterior)\n- Comprender la diferencia entre velocidad de producción y calidad de solución.",
    "ejemplo": "- Generar un prototipo inicial a partir de un caso.\n- Evaluarlo con criterios de utilidad, coherencia, consistencia y adecuación al problema. (ya han visto leyes de UX)",
    "indice": ""
  },
  {
    "id": "s16",
    "bloque": "2.Estado actual del Diseño de Producto Digital y AI-Native Thinking",
    "tipo": "Sesión de contenido",
    "titulo": "AI-native mindset y herramientas base (Lovable, Figma y Claude) (II)",
    "profesor": "Germán Enguix",
    "comunicada": "2026-10-20",
    "confirmada": "2026-10-20",
    "objetivos": "Principal: Diseñar un flujo de trabajo combinando herramientas generativas que mejore eficiencia.\n- Conocer las fortalezas y limitaciones relativas de distintas herramientas.\n- Identificar puntos de revisión, validación y decisión humana.",
    "ejemplo": "- Representar un workflow con entradas, herramientas, transferencias, controles y resultados.\n- Aplicarlo a una tarea y valorar ahorro real, calidad y riesgos.",
    "indice": ""
  },
  {
    "id": "s17",
    "bloque": "2.Estado actual del Diseño de Producto Digital y AI-Native Thinking",
    "tipo": "Sesión de contenido",
    "titulo": "Vibe coding con Figma Make y Claude",
    "profesor": "Manu Lorenzo",
    "comunicada": "2026-10-21",
    "confirmada": "2026-10-21",
    "objetivos": "Principal: Convertir un diseño en un prototipo funcional mediante generación de código y evaluar su viabilidad\n- Comprender qué puede y qué no puede resolver el vibe coding.\n- Reconocer errores de estructura, accesibilidad (lo ven 2 clases después), rendimiento y mantenibilidad.",
    "ejemplo": "- Construir e iterar un prototipo navegable.\n- Elaborar una revisión de limitaciones y requisitos para llevarlo a producción.",
    "indice": ""
  },
  {
    "id": "s18",
    "bloque": "2.Estado actual del Diseño de Producto Digital y AI-Native Thinking",
    "tipo": "Sesión de contenido",
    "titulo": "Diseño inclusivo, usable y accesible (WCAG 3.0)",
    "profesor": "Juan Luis Vilar",
    "comunicada": "2026-10-22",
    "confirmada": "2026-10-22",
    "objetivos": "Principal: Priorizar y corregir barreras de accesibilidad considerando su impacto real en personas, tareas y contextos de uso.\n- Conocer los principios esenciales de accesibilidad y criterios WCAG aplicables.\n- Comprender la diferencia entre accesibilidad, usabilidad e inclusión.\n- Evaluar un prototipo hecho con IA (lo han hecho en la clase anterior) frente a criterios de accesibilidad.",
    "ejemplo": "- Realizar una auditoría breve .\n- Implementar correcciones a un prototipo para adaptarlo a la normativa de accesibilidad.",
    "indice": "- Introducción.\n- Concepto de accesibilidad TIC.\n- Accesibilidad, usabilidad e inclusión\n- Tipos de discapacidad y como usan los usuarios con discapacidad las TIC.\n- Practica de productos de apoyo\n- Marco normativo.\n- Directiva (UE) 2019/882: Ley 11/2023\n- UNE-en 301 549: Explicación y apartados.\n- W3C./ WCAG 2.2.\n- ¿Qué es el W3C?\n- ¿Qué son las WCAG?\n- Los cuatro principios (POUR).\n- Niveles de conformidad (A, AA y AAA).\n- Cómo se organizan las WCAG (principios → pautas → criterios de éxito).\n- Relación entre las WCAG y la UNE-EN 301 549.\n- Severidad o impacto.\n- WCAG 2.2 explicadas desde la práctica (explicación de los criterios visuales y más frecuentes desde ejemplos prácticos)\n- Contraste suficiente.\n- No depender solo del color.\n- Texto alternativo en imágenes.\n- Estructura correcta (encabezados).\n- Enlaces descriptivos.\n- Navegación completamente con teclado.\n- Foco visible.\n- Formularios accesibles.\n- Mensajes de error comprensibles.\n- Objetivos táctiles suficientemente grandes.\n- Elementos multimedia.\n- Inteligencia Artificial y accesibilidad\n- ¿Cómo puede ayudar la IA?\n- ¿Cuáles son sus limitaciones?\n- Buenas prácticas para un uso responsable.\n- Taller: auditoría de un prototipo IA. Se trabajara por grupos. En este taller los alumnos debe identificar las posibles barreras de accesibilidad que tienen sus prototipos, como afectan a los usuarios con discapacidad, prioridad y posibles soluciones.\n- Puesta en común. Donde cada grupo explicara:\n- Barreras encontradas\n- Prioridad\n- Solución propuesta"
  },
  {
    "id": "s19",
    "bloque": "2.Estado actual del Diseño de Producto Digital y AI-Native Thinking",
    "tipo": "Sesión de contenido",
    "titulo": "Tendencias e innovación (RA, VI, IA, VUI).",
    "profesor": "Adrián Martín",
    "comunicada": "2026-10-26",
    "confirmada": "2026-10-26",
    "objetivos": "Principal: Explorar soluciones innovadoras que trasciendan las interfaces de pantalla y aprovechen nuevas tecnologías y modos de interacción para resolver problemas reales.\n- Comprender cómo una nueva tecnología puede transformar no solo la interfaz, sino también la experiencia, el servicio o el modelo de solución.\n- Distinguir entre una innovación tecnológica con valor y una aplicación novedosa pero innecesaria.\n- Identificar qué problemas pueden resolverse mejor mediante experiencias físicas, contextuales o híbridas que mediante una pantalla tradicional.",
    "ejemplo": "- Partir de un problema de usuario ya definido y generar varias soluciones que no dependan exclusivamente de una interfaz gráfica o conversacional.",
    "indice": ""
  },
  {
    "id": "s20",
    "bloque": "3. Research y validación con usuarios",
    "tipo": "Skills",
    "titulo": "GESTIÓNATE: AUTONOMÍA Y RENDIMIENTO",
    "profesor": "Juan Portillo",
    "comunicada": "2026-10-27",
    "confirmada": "2026-10-27",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s21",
    "bloque": "3. Research y validación con usuarios",
    "tipo": "Sesión de contenido",
    "titulo": "Métodos de investigación generativa (cualitativo y cuantitativo) (I)",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "2026-10-28",
    "confirmada": "2026-10-28",
    "objetivos": "Principal: Traducir una necesidad de negocio o producto en objetivos y preguntas de investigación y segmentos de usuario, capaces de orientar una decisión.\n- Comprender la diferencia entre objetivo, pregunta y diferentes métodos de observación y de pregunta.\n- Conocer cuándo conviene investigación cualitativa, cuantitativa o mixta.",
    "ejemplo": "- Elaborar un research brief con contexto, objetivos, preguntas, hipótesis y decisiones que debe informar.\n- Justificar el enfoque metodológico elegido.",
    "indice": ""
  },
  {
    "id": "s22",
    "bloque": "3. Research y validación con usuarios",
    "tipo": "Sesión de contenido",
    "titulo": "Métodos de investigación generativa (cualitativo y cuantitativo) (II)",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "2026-10-29",
    "confirmada": "2026-10-29",
    "objetivos": "Principal: Traducir una necesidad de negocio o producto en objetivos y preguntas de investigación y segmentos de usuario, capaces de orientar una decisión.\n- Comprender la diferencia entre objetivo, pregunta y diferentes métodos de observación y de pregunta.\n- Conocer cuándo conviene investigación cualitativa, cuantitativa o mixta.",
    "ejemplo": "- Elaborar un research brief con contexto, objetivos, preguntas, hipótesis y decisiones que debe informar.\n- Justificar el enfoque metodológico elegido.",
    "indice": ""
  },
  {
    "id": "s23",
    "bloque": "3. Research y validación con usuarios",
    "tipo": "Sesión de contenido",
    "titulo": "Fuentes de datos en empresa",
    "profesor": "Pablo de la Fuente",
    "comunicada": "2026-11-02",
    "confirmada": "2026-11-02",
    "objetivos": "Principal: Descubrir diferentes fuentes de datos y saber qué datos objetivos pueden obtenerse, tanto de navegación y audiencia como para una investigación generativa. Combinar evidencia cualitativa y cuantitativa para construir una comprensión más fiable.\n- Conocer las principales fuentes internas: analítica, CRM, soporte, ventas, operaciones y research previo.\n- Comprender los límites y sesgos de cada fuente.",
    "ejemplo": "- Crear un mapa de evidencias procedentes de al menos dos fuentes.\n- Identificar coincidencias, contradicciones, vacíos y nuevas preguntas.",
    "indice": ""
  },
  {
    "id": "s24",
    "bloque": "3. Research y validación con usuarios",
    "tipo": "Empleabilidad",
    "titulo": "FERIA DE EMPLEO",
    "profesor": "",
    "comunicada": "2026-11-03",
    "confirmada": "2026-11-03",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s25",
    "bloque": "3. Research y validación con usuarios",
    "tipo": "Sesión de contenido",
    "titulo": "Obtención de insights e hipótesis",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "2026-11-04",
    "confirmada": "2026-11-04",
    "objetivos": "Principal: Transformar datos y hallazgos en insights relevantes, oportunidades de diseño e hipótesis verificables.\n- Distinguir dato, hallazgo, patrón, insight, oportunidad e hipótesis.\n- Conocer criterios de priorización por relevancia, frecuencia, impacto y confianza.",
    "ejemplo": "- Obtener una tabla de datos, insights y oportunidades.\n- Priorizar oportunidades e hipótesis conectadas con decisiones de producto.",
    "indice": ""
  },
  {
    "id": "s26",
    "bloque": "3. Research y validación con usuarios",
    "tipo": "Sesión de contenido",
    "titulo": "Uso de la IA en procesos de research",
    "profesor": "Ana López Triguero",
    "comunicada": "2026-11-05",
    "confirmada": "2026-11-05",
    "objetivos": "Principal: Utilizar IA para acelerar la organización y síntesis del research sin perder trazabilidad con la evidencia original.\n- Conocer usos válidos de IA en transcripción, etiquetado, agrupación y síntesis.\n- Reconocer pérdida de matices, homogeneización y conclusiones no sustentadas.",
    "ejemplo": "- Crear un mapa de evidencias procedentes de al menos dos fuentes.\n- Identificar coincidencias, contradicciones, vacíos y nuevas preguntas.\n- Comparar una síntesis automática con los datos originales.\n- Corregirla, justificar cambios y señalar qué partes requieren revisión humana.",
    "indice": ""
  },
  {
    "id": "s27",
    "bloque": "3. Research y validación con usuarios",
    "tipo": "Sesión de contenido",
    "titulo": "Herramientas generativas: Elicit, Scite.ai, Perplexity",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "2026-11-09",
    "confirmada": "2026-11-09",
    "objetivos": "Principal: Seleccionar y verificar fuentes externas fiables para contextualizar una investigación o decisión de producto.\n- Conocer diferencias entre buscadores, asistentes y herramientas de evidencia científica.\n- Seleccionar la herramienta adecuada según la necesidad: descubrir fuentes;localizar evidencia académica;comprobar el respaldo o contradicción de un estudio;comparar documentos;sintetizar información ya recopilada.",
    "ejemplo": "- Elaborar un dossier breve que incluya: pregunta investigada;estrategia y herramientas utilizadas;fuentes seleccionadas y descartadas;criterio de fiabilidad;principales hallazgos;contradicciones y limitaciones;\n- implicaciones para la decisión de producto.",
    "indice": ""
  },
  {
    "id": "s28",
    "bloque": "3. Research y validación con usuarios",
    "tipo": "Empleabilidad",
    "titulo": "Taller Procesos de selección II",
    "profesor": "",
    "comunicada": "",
    "confirmada": "",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s29",
    "bloque": "3. Research y validación con usuarios",
    "tipo": "Sesión de contenido",
    "titulo": "Básicos de Figma (IV)",
    "profesor": "Paula Girela González",
    "comunicada": "2026-11-10",
    "confirmada": "2026-11-10",
    "objetivos": "Principal: Construir un flujo responsive de varias pantallas\n- Comprender auto layout y componentes y variantes.\n- Reconocer diferencias entre redimensionar, reorganizar y cambiar comportamiento.",
    "ejemplo": "- Prototipar un flujo adaptable a distintos tamaños.",
    "indice": ""
  },
  {
    "id": "s30",
    "bloque": "3. Research y validación con usuarios",
    "tipo": "Sesión de contenido",
    "titulo": "Herramientas evaluativas: Maze, Usertesting, GA, Hotjar AI (I).",
    "profesor": "Pablo de la Fuente",
    "comunicada": "2026-11-11",
    "confirmada": "2026-11-11",
    "objetivos": "Principal: Diseñar un test de usabilidad no moderado alineado con una hipótesis, tareas críticas y criterios de éxito.\n- Comprender ventajas y límites de las pruebas no moderadas.\n- Conocer métricas de finalización, tiempo, error, abandono y percepción.",
    "ejemplo": "- Configurar un test con participantes, tareas, preguntas y métricas.\n- Revisar si el diseño del test permite realmente responder a la hipótesis.",
    "indice": ""
  },
  {
    "id": "s31",
    "bloque": "3. Research y validación con usuarios",
    "tipo": "Sesión de contenido",
    "titulo": "Herramientas evaluativas: Maze, Usertesting, GA, Hotjar AI (II).",
    "profesor": "Pablo de la Fuente",
    "comunicada": "2026-11-12",
    "confirmada": "2026-11-12",
    "objetivos": "Principal: Interpretar datos de comportamiento para priorizar decisiones de diseño sin confundir correlación con causa.\n- Comprender mapas de calor, funnels, eventos y resultados de tests.\n- Reconocer sesgos de interpretación y limitaciones de las herramientas.",
    "ejemplo": "- Elaborar un informe que conecte datos de al menos dos fuentes con fricciones e hipótesis.\n- Priorizar cambios y evidencia adicional necesaria.\n- HAcer una correcta presentación de resultados proponiendo oportunidades y prioridades basadas en datos.",
    "indice": ""
  },
  {
    "id": "s32",
    "bloque": "3. Research y validación con usuarios",
    "tipo": "Sesión de contenido",
    "titulo": "Ética y sesgos en investigación con usuarios",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "2026-11-16",
    "confirmada": "2026-11-16",
    "objetivos": "Principal: Diseñar una investigación responsable anticipando riesgos de sesgo, privacidad, consentimiento y representación.\n- Conocer sesgos de muestra, confirmación, moderación y análisis.\n- Comprender consentimiento informado, minimización de datos y protección de participantes.",
    "ejemplo": "- Elaborar un protocolo ético para el proyecto.\n- Identificar limitaciones y medidas preventivas antes de ejecutar la investigación.",
    "indice": ""
  },
  {
    "id": "s33",
    "bloque": "3. Research y validación con usuarios",
    "tipo": "Proyecto MUX",
    "titulo": "LANZAMIENTO MUX PROJECT: RESEARCH",
    "profesor": "",
    "comunicada": "",
    "confirmada": "",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s34",
    "bloque": "3. Research y validación con usuarios",
    "tipo": "Coordinación",
    "titulo": "DINÁMICA COORDINACIÓN + comentar Los monstruos y el gimnasio",
    "profesor": "Paula Girela González",
    "comunicada": "2026-11-17",
    "confirmada": "2026-11-17",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s35",
    "bloque": "4. Innovación y pensamiento estratégico",
    "tipo": "Sesión de contenido",
    "titulo": "Diseño especulativo y futuros",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "2026-11-18",
    "confirmada": "2026-11-18",
    "objetivos": "Principal: Construir escenarios futuros plausibles que ayuden a cuestionar supuestos presentes y orientar decisiones actuales.\n- Comprender diferencia entre predicción, escenario, señal y especulación.\n- Conocer técnicas básicas de exploración de futuros.",
    "ejemplo": "- Crear un escenario fundamentado en señales e incertidumbres.\n- Extraer riesgos, oportunidades y decisiones accionables para el presente.",
    "indice": ""
  },
  {
    "id": "s36",
    "bloque": "4. Innovación y pensamiento estratégico",
    "tipo": "Sesión de contenido",
    "titulo": "Design Thinking avanzado  (Journey AS IS, journey TO BE, JTBD)",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "2026-11-19",
    "confirmada": "2026-11-19",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s37",
    "bloque": "4. Innovación y pensamiento estratégico",
    "tipo": "Sesión de contenido",
    "titulo": "Design Thinking avanzado (Journey AS IS, journey TO BE, JTBD) II",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "2026-11-23",
    "confirmada": "2026-11-23",
    "objetivos": "Principal: Representar la experiencia actual y formular los progresos y barreras que el usuario experimenta a partir de evidencias reales.\n- Comprender la función de journey AS IS y Jobs To Be Done.\n- Distinguir tareas, necesidades, motivaciones, resultados esperados y circunstancias.",
    "ejemplo": "- Construir un journey AS IS trazable con la investigación.\n- Formular JTBD y señalar evidencias, tensiones y puntos de dolor.",
    "indice": ""
  },
  {
    "id": "s38",
    "bloque": "4. Innovación y pensamiento estratégico",
    "tipo": "Proyecto MUX",
    "titulo": "JORNADA DE TRABAJO MUX PROJECT: RESEARCH",
    "profesor": "",
    "comunicada": "2026-11-24",
    "confirmada": "2026-11-24",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s39",
    "bloque": "4. Innovación y pensamiento estratégico",
    "tipo": "Skills",
    "titulo": "TALLER COMUNICACIÓN",
    "profesor": "Toni Cantó",
    "comunicada": "2026-11-25",
    "confirmada": "2026-11-25",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s40",
    "bloque": "4. Innovación y pensamiento estratégico",
    "tipo": "Sesión de contenido",
    "titulo": "Técnicas de ideación y co-creación",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "2026-11-26",
    "confirmada": "2026-11-26",
    "objetivos": "Principal: Facilitar un workshop de cocreación que genere diversidad de alternativas y permita converger (mención doble diamante)\n- Conocer técnicas divergentes y convergentes y cuándo aplicar cada una.\n- Comprender el papel del facilitador y los sesgos grupales.",
    "ejemplo": "- Diseñar y facilitar una dinámica.\n- Documentar resultados, criterios de priorización, decisiones y limitaciones de la sesión.",
    "indice": ""
  },
  {
    "id": "s41",
    "bloque": "4. Innovación y pensamiento estratégico",
    "tipo": "Proyecto MUX",
    "titulo": "JORNADA DE TRABAJO MUX PROJECT: RESEARCH",
    "profesor": "",
    "comunicada": "2026-11-30",
    "confirmada": "2026-11-30",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s42",
    "bloque": "4. Innovación y pensamiento estratégico",
    "tipo": "Proyecto MUX",
    "titulo": "DEFENSA MUX PROJECT: RESEARCH",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "",
    "confirmada": "",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s43",
    "bloque": "4. Innovación y pensamiento estratégico",
    "tipo": "Sesión de contenido",
    "titulo": "Modelo de Calidad Total",
    "profesor": "Josep Martínez",
    "comunicada": "2026-12-02",
    "confirmada": "2026-12-02",
    "objetivos": "Principal: Analizar un problema de producto desde el Modelo de Calidad Total para formularlo de manera sistémica, basada en hechos y compatible con las necesidades de los cinco componentes.\n- Comprender los cinco componentes y reconocer cómo una decisión centrada únicamente en el usuario puede generar problemas de ejecución, viabilidad o sostenibilidad.\n- Identificar los paradigmas y supuestos desde los que se interpreta un brief, diferenciando hechos, opiniones, síntomas y causas.\n- Aplicar verdades universales como contrastación, hechos, no palabras y todo efecto tiene una causa para cuestionar el problema antes de diseñar.",
    "ejemplo": "- Investigar y comparar al menos dos metodologías mediante criterios comunes: finalidad, fases, contexto, ventajas y limitaciones.\n- Justificar el uso o no uso de IA en las fases de una metodología elegida para un caso concreto.",
    "indice": "- Misión y Visión\n- Verdades Universales\n- Paradigmas"
  },
  {
    "id": "s44",
    "bloque": "4. Innovación y pensamiento estratégico",
    "tipo": "Institucional / calendario",
    "titulo": "Excursion Jarrods + ejercicio",
    "profesor": "Paula Girela González",
    "comunicada": "",
    "confirmada": "",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s45",
    "bloque": "4. Innovación y pensamiento estratégico",
    "tipo": "Sesión de contenido",
    "titulo": "Diseño dinámico multiusuario, multicanal y multidispositivo",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "2026-12-09",
    "confirmada": "2026-12-09",
    "objetivos": "Principal: Diseñar una experiencia coherente entre usuarios, canales y dispositivos adaptando la interacción a cada contexto.\n- Comprender continuidad, sincronización, traspaso y consistencia entre canales.\n- Identificar roles, permisos y necesidades distintas entre usuarios.",
    "ejemplo": "- Representar un flujo multicanal y multiusuario.\n- Justificar qué elementos se mantienen, cuáles cambian y cómo se gestionan las transiciones.",
    "indice": ""
  },
  {
    "id": "s46",
    "bloque": "4. Innovación y pensamiento estratégico",
    "tipo": "Sesión de contenido",
    "titulo": "Tipos de IA y aplicaciones a producto",
    "profesor": "Carolina Barbosa",
    "comunicada": "2026-12-10",
    "confirmada": "2026-12-10",
    "objetivos": "Principal: Conocer y seleccionar el tipo de IA adecuado para una necesidad de producto considerando valor, datos, riesgos y viabilidad.\n- Conocer diferencias entre IA predictiva, generativa, recomendación, clasificación y agentes.\n- Comprender diferencias entre asistente, chatbot, automatización y agente.\n- Conocer condiciones mínimas de autonomía, objetivos, herramientas y contexto\n- Comprender requisitos de datos, supervisión y evaluación.",
    "ejemplo": "- Comparar la solución entre diferentes IAs y sin IA y justificar la elección.",
    "indice": ""
  },
  {
    "id": "s47",
    "bloque": "4. Innovación y pensamiento estratégico",
    "tipo": "Extra",
    "titulo": "TALK: De la idea al producto (Startups)",
    "profesor": "",
    "comunicada": "",
    "confirmada": "",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s48",
    "bloque": "4. Innovación y pensamiento estratégico",
    "tipo": "Sesión de contenido",
    "titulo": "Behavioral design + IA aplicada (I)",
    "profesor": "María Corrales",
    "comunicada": "2026-12-15",
    "confirmada": "2026-12-15",
    "objetivos": "Principal: Analizar cómo contexto, motivación, capacidad y arquitectura de decisión influyen en el comportamiento de los usuarios.\n- Conocer principios básicos de comportamiento y formación de hábitos.\n- Distinguir barreras, motivadores, sesgos y consecuencias.",
    "ejemplo": "- Realizar un diagnóstico conductual de una experiencia.\n- Identificar dónde intervenir y qué evidencia falta antes de diseñar un nudge.",
    "indice": "- Introducción al behavioral design aplicado a UX/UI\n- Relación entre research, comportamiento y diseño de experiencias\n- Modelos básicos de comportamiento: motivación, capacidad, oportunidad y contexto\n- Behavioral mapping: cómo mapear momentos de decisión dentro de un flujo digital\n- Identificación de barreras, motivadores, sesgos y consecuencias\n- Formación de hábitos en productos digitales\n- Contextos culturales y arquetipos conductuales\n- Uso de IA para sintetizar research, detectar patrones y formular hipótesis conductuales\n- Del diagnóstico conductual a la oportunidad de diseño: cómo pasar del behavioral map a una mejora de la experiencia digital\n- Diseño de nudges responsables: qué es un nudge y tipos de intervenciones conductuales en UX/UI\n- Psicología de precios y percepción de valor\n- Patrones oscuros y límites éticos del diseño conductual\n- Riesgos de la personalización automatizada con IA\n- Evaluación de impacto en diferentes segmentos de usuario\n- CRO como capa complementaria de medición y aprendizaje\n- Definición básica de hipótesis y métricas en las que fijarse"
  },
  {
    "id": "s49",
    "bloque": "4. Innovación y pensamiento estratégico",
    "tipo": "Sesión de contenido",
    "titulo": "Behavioral design + IA aplicada (ÏI)",
    "profesor": "María Corrales",
    "comunicada": "2026-12-16",
    "confirmada": "2026-12-16",
    "objetivos": "Principal: Conocer CRO. Diseñar una intervención conductual ética y evaluar el límite entre ayuda, personalización y manipulación.\n- Conocer patrones oscuros y criterios éticos de intervención.\n- Comprender riesgos de personalización automatizada.\n- Apoyarse de behavioral para construir oportunidades de diseño",
    "ejemplo": "- Diseñar un nudge con objetivo, mecanismo, impacto esperado y salvaguardas.\n- Someterlo a una revisión ética y proponer cómo medir efectos deseados y no deseados.\n- Evaluar imparto en diferentes segmentos de usuario.",
    "indice": "- Introducción al behavioral design aplicado a UX/UI\n- Relación entre research, comportamiento y diseño de experiencias\n- Modelos básicos de comportamiento: motivación, capacidad, oportunidad y contexto\n- Behavioral mapping: cómo mapear momentos de decisión dentro de un flujo digital\n- Identificación de barreras, motivadores, sesgos y consecuencias\n- Formación de hábitos en productos digitales\n- Contextos culturales y arquetipos conductuales\n- Uso de IA para sintetizar research, detectar patrones y formular hipótesis conductuales\n- Del diagnóstico conductual a la oportunidad de diseño: cómo pasar del behavioral map a una mejora de la experiencia digital\n- Diseño de nudges responsables: qué es un nudge y tipos de intervenciones conductuales en UX/UI\n- Psicología de precios y percepción de valor\n- Patrones oscuros y límites éticos del diseño conductual\n- Riesgos de la personalización automatizada con IA\n- Evaluación de impacto en diferentes segmentos de usuario\n- CRO como capa complementaria de medición y aprendizaje\n- Definición básica de hipótesis y métricas en las que fijarse"
  },
  {
    "id": "s50",
    "bloque": "4. Innovación y pensamiento estratégico",
    "tipo": "Proyecto MUX",
    "titulo": "LANZAMIENTO TFM: STARTUP",
    "profesor": "",
    "comunicada": "",
    "confirmada": "",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s51",
    "bloque": "4. Innovación y pensamiento estratégico",
    "tipo": "Coordinación",
    "titulo": "DINÁMICA COORDINACIÓN",
    "profesor": "Paula Girela González",
    "comunicada": "2026-12-17",
    "confirmada": "2026-12-17",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s52",
    "bloque": "4. Innovación y pensamiento estratégico",
    "tipo": "Proyecto MUX",
    "titulo": "JORNADA DE TRABAJO STARTUP PROJECT (con startup)",
    "profesor": "",
    "comunicada": "",
    "confirmada": "",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s53",
    "bloque": "4. Innovación y pensamiento estratégico",
    "tipo": "Sesión de contenido",
    "titulo": "Estrategia de innovación y nuevos modelos de negocio",
    "profesor": "Miguel Castrillo",
    "comunicada": "2027-01-12",
    "confirmada": "2027-01-12",
    "objetivos": "Principal: Entender diferentes modelos de negocio. Proponer una innovación que conecte necesidad de mercado, propuesta de valor, capacidades organizativas y sostenibilidad económica.\n- Comprender los elementos de un modelo de negocio y sus interdependencias.\n- Distinguir innovación de producto, servicio, proceso y modelo.",
    "ejemplo": "- Representar el modelo actual y una alternativa futura.\n- Explicitar hipótesis críticas, riesgos y condiciones para su viabilidad.",
    "indice": ""
  },
  {
    "id": "s54",
    "bloque": "4. Innovación y pensamiento estratégico",
    "tipo": "Sesión de contenido",
    "titulo": "Service Design aplicado a productos digitales (I)",
    "profesor": "Miguel Castrillo",
    "comunicada": "2027-01-13",
    "confirmada": "2027-01-13",
    "objetivos": "Principal: Representar cómo se produce una experiencia relacionando acciones del usuario, frontstage, backstage y procesos de soporte.\n- Comprender la lógica y utilidad del service blueprint.\n- Diferenciar evidencia visible, interacción, operación y soporte.",
    "ejemplo": "- Construir el blueprint AS IS de un servicio real. (ya hicieron AS IS y JTBD)\n- Identificar fallos, dependencias y puntos sin evidencia.",
    "indice": ""
  },
  {
    "id": "s55",
    "bloque": "4. Innovación y pensamiento estratégico",
    "tipo": "Sesión de contenido",
    "titulo": "Service Design aplicado a productos digitales (II)",
    "profesor": "Miguel Castrillo",
    "comunicada": "2027-01-14",
    "confirmada": "2027-01-14",
    "objetivos": "Principal: Diseñar mejoras coordinadas del servicio que resuelvan fallos sistémicos más allá de la interfaz.\n- Comprender cómo una mejora de experiencia afecta a procesos, roles y tecnología.\n- Priorizar intervenciones por impacto, viabilidad y dependencia.",
    "ejemplo": "- Elaborar un blueprint TO BE.\n- Definir intervención, responsables, dependencias, riesgos e impacto esperado.",
    "indice": ""
  },
  {
    "id": "s56",
    "bloque": "4. Innovación y pensamiento estratégico",
    "tipo": "Sesión de contenido",
    "titulo": "Internacionalización y localización",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "2027-01-18",
    "confirmada": "2027-01-18",
    "objetivos": "Principal: Adaptar un producto/Servicio a un nuevo mercado considerando idioma, cultura, regulación, comportamiento y arquitectura del sistema.\n- Conocer diferencias entre traducción, localización e internacionalización.\n- Comprender el impacto de formatos, contenido, convenciones y requisitos normativos.",
    "ejemplo": "- Realizar un análisis de adaptación para un mercado concreto.\n- Identificar cambios en experiencia, contenidos, componentes y sistema de diseño.",
    "indice": ""
  },
  {
    "id": "s57",
    "bloque": "4. Innovación y pensamiento estratégico",
    "tipo": "Proyecto MUX",
    "titulo": "LANZAMIENTO MUX PROJECT: INNOVACIÓN",
    "profesor": "",
    "comunicada": "",
    "confirmada": "",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s58",
    "bloque": "5. Diseño de interfaces",
    "tipo": "Sesión de contenido",
    "titulo": "Arquitectura de información",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "2027-01-20",
    "confirmada": "2027-01-20",
    "objetivos": "Principal: Organizar y etiquetar contenidos de acuerdo con los modelos mentales, necesidades y tareas de los usuarios.\n- Comprender inventario, taxonomía, agrupación, jerarquía, etiquetado y encontrabilidad.\n- Conocer técnicas de card sorting y tree testing.",
    "ejemplo": "- Construir una propuesta de arquitectura.\n- Validarla, interpretar resultados y ajustar decisiones de estructura y nomenclatura.",
    "indice": ""
  },
  {
    "id": "s59",
    "bloque": "5. Diseño de interfaces",
    "tipo": "Sesión de contenido",
    "titulo": "Diagramas de flujo",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "2027-01-21",
    "confirmada": "2027-01-21",
    "objetivos": "Principal: Representar la lógica completa de una interacción incluyendo decisiones, errores, excepciones y salidas.\n- Conocer símbolos y convenciones básicas de diagramación.\n- Comprender la diferencia entre flujo ideal, alternativo y de recuperación.",
    "ejemplo": "- Crear un flujo utilizable por diseño, producto y desarrollo.\n- Revisarlo para detectar huecos, dependencias y casos no contemplados.",
    "indice": ""
  },
  {
    "id": "s60",
    "bloque": "5. Diseño de interfaces",
    "tipo": "Proyecto MUX",
    "titulo": "JORNADA DE TRABAJO MUX PROJECT: INNOVACIÓN",
    "profesor": "",
    "comunicada": "",
    "confirmada": "",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s61",
    "bloque": "5. Diseño de interfaces",
    "tipo": "Sesión de contenido",
    "titulo": "Modelos de navegación",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "2027-01-26",
    "confirmada": "2027-01-26",
    "objetivos": "Principal: Seleccionar y justificar un modelo de navegación acorde con la arquitectura, frecuencia de uso, profundidad y tareas principales.\n- Conocer modelos jerárquicos, , navegación contextual y búsqueda.\n- Comprender sus ventajas, límites y patrones de uso.",
    "ejemplo": "- Comparar al menos dos modelos para un caso.\n- Documentar la elección, la alternativa descartada y los criterios utilizados.",
    "indice": ""
  },
  {
    "id": "s62",
    "bloque": "5. Diseño de interfaces",
    "tipo": "Sesión de contenido",
    "titulo": "Bocetado, wireframes y prototipado con herramientas generativas",
    "profesor": "Raúl Marín Calleja",
    "comunicada": "2027-01-27",
    "confirmada": "2027-01-27",
    "objetivos": "Principal: Explorar varias alternativas en baja fidelidad digitalizadas y subir fidelidad con herramientas de IA\n- Comprender la función del boceto y wireframe antes del diseño visual.\n- Conocer usos y límites de las herramientas generativas en ideación.",
    "ejemplo": "- Producir alternativas manuales y asistidas por IA.\n- Compararlas con criterios explícitos y justificar la dirección elegida.",
    "indice": ""
  },
  {
    "id": "s63",
    "bloque": "5. Diseño de interfaces",
    "tipo": "Sesión de contenido",
    "titulo": "Diseño de interacción en pantallas con Figma y Figma Make",
    "profesor": "Raúl Marín Calleja",
    "comunicada": "2027-01-28",
    "confirmada": "2027-01-28",
    "objetivos": "Principal: Diseñar interacciones con propósito para el usuario y para el negocio.\n- Conocer principios de feedback, visibilidad del estado y prevención de errores.\n- Comprender diferencias entre animación decorativa y comportamiento funcional.",
    "ejemplo": "- Prototipar una microinteracción manualmente y con IA.\n- Comparar ambos resultados según claridad, control, accesibilidad y coste.",
    "indice": ""
  },
  {
    "id": "s64",
    "bloque": "5. Diseño de interfaces",
    "tipo": "Proyecto MUX",
    "titulo": "JORNADA DE TRABAJO MUX PROJECT: INNOVACIÓN",
    "profesor": "",
    "comunicada": "",
    "confirmada": "",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s65",
    "bloque": "5. Diseño de interfaces",
    "tipo": "Proyecto MUX",
    "titulo": "DEFENSA MUX PROJECT: INNOVACIÓN",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "",
    "confirmada": "",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s66",
    "bloque": "5. Diseño de interfaces",
    "tipo": "Sesión de contenido",
    "titulo": "Interfaces adaptativas y dinámicas",
    "profesor": "Carolina Barbosa",
    "comunicada": "2027-02-03",
    "confirmada": "2027-02-03",
    "objetivos": "Principal: Definir cómo debe comportarse una interfaz ante diferentes contenidos, estados, tamaños y condiciones de uso.\n- Conocer estados vacío, carga, error, parcial, éxito y permisos.\n- Comprender principios responsive y adaptación por contexto.",
    "ejemplo": "- Diseñar y documentar un componente o pantalla en distintos estados con herramientas de IA.\n- Probar casos extremos y ajustar reglas de comportamiento.",
    "indice": ""
  },
  {
    "id": "s67",
    "bloque": "5. Diseño de interfaces",
    "tipo": "Sesión de contenido",
    "titulo": "Sistemas de diseño atómico",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "2027-02-04",
    "confirmada": "2027-02-04",
    "objetivos": "Principal: Decidir qué elementos conviene sistematizar para aumentar consistencia, reutilización y escalabilidad.\n- Comprender atomic design como modelo de clasificación, no como fin en sí mismo.\n- Diferenciar y valorar los fundamentos: consistencia, escalabilidad y atomicidad.",
    "ejemplo": "- Crear un inventario de interfaz y proponer una estructura inicial del sistema.\n- Justificar niveles, relaciones y criterios de inclusión.",
    "indice": ""
  },
  {
    "id": "s68",
    "bloque": "5. Diseño de interfaces",
    "tipo": "Proyecto MUX",
    "titulo": "JORNADA DE TRABAJO STARTUP PROJECT (tutores/solos)",
    "profesor": "",
    "comunicada": "",
    "confirmada": "",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s69",
    "bloque": "5. Diseño de interfaces",
    "tipo": "Sesión de contenido",
    "titulo": "Uso de sistemas  de diseño para composición de interfaces",
    "profesor": "Carlos Velasco",
    "comunicada": "2027-02-09",
    "confirmada": "",
    "objetivos": "Principal: Construir interfaces coherentes utilizando componentes existentes y resolver necesidades nuevas sin romper el sistema.\n- Comprender reglas de composición, variantes y extensibilidad.\n- Distinguir reutilización válida, modificación local y necesidad de nuevo componente.",
    "ejemplo": "- Componer una pantalla con un sistema existente.\n- Detectar una inconsistencia o gap y proponer una solución compatible con el sistema.",
    "indice": ""
  },
  {
    "id": "s70",
    "bloque": "5. Diseño de interfaces",
    "tipo": "Sesión de contenido",
    "titulo": "Tokenización y documentación de sistemas de diseño",
    "profesor": "Carlos Velasco",
    "comunicada": "2027-02-10",
    "confirmada": "",
    "objetivos": "Principal: Definir y documentar reglas reutilizables que mantengan consistencia entre diseño, código y evolución del producto.\n- Conocer la función de tokens, propiedades, variantes y documentación.\n- Comprender qué información necesita diseño y qué necesita desarrollo.",
    "ejemplo": "- Crear un conjunto básico de tokens.\n- Documentar un componente incluyendo uso, estados, variantes, accesibilidad y restricciones.",
    "indice": ""
  },
  {
    "id": "s71",
    "bloque": "5. Diseño de interfaces",
    "tipo": "Skills",
    "titulo": "CONéCTATE: COMUNICACIÓN Y ADAPTACIÓN",
    "profesor": "Juan Portillo",
    "comunicada": "2027-02-11",
    "confirmada": "2027-02-11",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s72",
    "bloque": "5. Diseño de interfaces",
    "tipo": "Sesión de contenido",
    "titulo": "Sistemas de diseño en Figma vs Claude Design (I)",
    "profesor": "Carlos Velasco",
    "comunicada": "2027-02-15",
    "confirmada": "",
    "objetivos": "Principal: Construir el mismo componente mediante un proceso manual y uno generativo manteniendo requisitos equivalentes.\n- Comprender qué aspectos debe controlar un sistema de diseño.\n- Conocer capacidades y límites de ambos entornos.",
    "ejemplo": "- Definir requisitos comunes y construir el componente en ambos enfoques.\n- Registrar tiempos, decisiones, errores y necesidad de intervención.",
    "indice": ""
  },
  {
    "id": "s73",
    "bloque": "5. Diseño de interfaces",
    "tipo": "Sesión de contenido",
    "titulo": "Ejercicio Sistemas de diseño en Figma vs Claude Design (II)",
    "profesor": "Alba Rozas",
    "comunicada": "2027-02-16",
    "confirmada": "",
    "objetivos": "Principal: Recomendar cuándo utilizar cada enfoque según control, mantenibilidad, consistencia, accesibilidad, colaboración y conexión con código.\n- Analizar cómo cada herramienta gestiona componentes, variantes, estados, tokens, documentación y reutilización dentro de un sistema de diseño.\n- Identificar qué grado de control, trazabilidad y supervisión humana requiere cada herramienta para evitar inconsistencias o deuda de diseño.\n- Reconocer en qué contextos conviene trabajar manualmente, apoyarse en IA o combinar ambos.",
    "ejemplo": "- Justificar una elección de herramienta en función del tipo de producto, madurez del equipo, complejidad del sistema y necesidades de mantenimiento.\n- DEsglosar una interfaz en elementos de diseño atómico.\n- Componer una interfaz partiendo de un sistema de diseño.",
    "indice": ""
  },
  {
    "id": "s74",
    "bloque": "5. Diseño de interfaces",
    "tipo": "Sesión de contenido",
    "titulo": "VUI y nuevos modos de interacción (I)",
    "profesor": "Antonio Bueno",
    "comunicada": "2027-02-17",
    "confirmada": "2027-02-17",
    "objetivos": "Principal: Diseñar la estructura de una conversación considerando arquitectura, intención, contexto, turnos y expectativas del usuario.\n- Conocer principios básicos del diseño conversacional.\n- Comprender intents, utterances, contexto y memoria.",
    "ejemplo": "- Diseñar el happy path de una interacción de voz o conversación.\n- Justificar tono, confirmaciones y cantidad de información.",
    "indice": ""
  },
  {
    "id": "s75",
    "bloque": "5. Diseño de interfaces",
    "tipo": "Sesión de contenido",
    "titulo": "VUI y nuevos modos de interacción (II)",
    "profesor": "Antonio Bueno",
    "comunicada": "2027-02-18",
    "confirmada": "2027-02-18",
    "objetivos": "Principal: Diseñar recuperación ante errores, ambigüedad, interrupciones y situaciones no contempladas.\n- Comprender fallback, desambiguación, reparación y escalado.\n- Reconocer límites de confianza y autonomía.",
    "ejemplo": "- Completar el flujo con errores y excepciones.\n- Incluir mecanismos de salida, ayuda y transferencia a atención humana.",
    "indice": ""
  },
  {
    "id": "s76",
    "bloque": "5. Diseño de interfaces",
    "tipo": "Sesión de contenido",
    "titulo": "DesignOps: Gestión y escalado inteligente y deuda de diseño",
    "profesor": "María Molinero",
    "comunicada": "2027-02-22",
    "confirmada": "",
    "objetivos": "Principal: Diagnosticar problemas operativos que reducen la calidad o velocidad del diseño y priorizar acciones de mejora.\n- Comprender deuda de diseño, gobernanza, contribución y mantenimiento.\n- Distinguir problema de interfaz de problema de operación del diseño.",
    "ejemplo": "- Crear un mapa de deuda y causas.\n- Proponer un plan priorizado con impacto, esfuerzo, responsables y seguimiento.",
    "indice": ""
  },
  {
    "id": "s77",
    "bloque": "5. Diseño de interfaces",
    "tipo": "Proyecto MUX",
    "titulo": "PUNTO CONTROL SPRINT STARTUP PROJECT (Research)",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "",
    "confirmada": "",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s78",
    "bloque": "5. Diseño de interfaces",
    "tipo": "Coordinación",
    "titulo": "DINÁMICA COORDINACIÓN + RECORDAR INDIVIDUAL",
    "profesor": "Paula Girela González",
    "comunicada": "",
    "confirmada": "",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s79",
    "bloque": "6. Tecnología para diseñadores",
    "tipo": "Sesión de contenido",
    "titulo": "Básicos de programación para corregir a la IA (I)",
    "profesor": "Sofía Choukrane",
    "comunicada": "2027-02-24",
    "confirmada": "2027-02-24",
    "objetivos": "Principal: Interpretar la estructura básica de HTML y CSS para comprender cómo se materializa una interfaz.\n- Conocer etiquetas, jerarquía, box model, selectores y propiedades esenciales.\n- Relacionar estructura y estilos con el resultado visual.",
    "ejemplo": "- Leer y comentar un fragmento de código.\n- Identificar qué partes corresponden a contenido, estructura, estilos y comportamiento visual.",
    "indice": ""
  },
  {
    "id": "s80",
    "bloque": "6. Tecnología para diseñadores",
    "tipo": "Proyecto MUX",
    "titulo": "JORNADA DE TRABAJO STARTUP PROJECT",
    "profesor": "",
    "comunicada": "2027-02-25",
    "confirmada": "2027-02-25",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s81",
    "bloque": "6. Tecnología para diseñadores",
    "tipo": "Sesión de contenido",
    "titulo": "Básicos de programación para corregir a la IA (II)",
    "profesor": "Sofía Choukrane",
    "comunicada": "2027-03-01",
    "confirmada": "2027-03-01",
    "objetivos": "Principal: Detectar y corregir errores básicos en código generado por IA sin depender de una nueva generación automática.\n- Comprender errores frecuentes de maquetación y estilos.\n- Aprender a inspeccionar y probar correcciones.\n- Saber hacer comprobaciones para diferentes resoluciones.",
    "ejemplo": "- Corregir una interfaz con errores.\n- Explicar causa, modificación realizada y efecto en el resultado.",
    "indice": ""
  },
  {
    "id": "s82",
    "bloque": "6. Tecnología para diseñadores",
    "tipo": "Sesión de contenido",
    "titulo": "Librerías de componentes",
    "profesor": "Sofía Choukrane",
    "comunicada": "2027-03-02",
    "confirmada": "2027-03-02",
    "objetivos": "Principal: Relacionar decisiones del sistema de diseño con las posibilidades y restricciones de una librería de componentes de código.\n- Conocer la lógica de librerías como shadcn y equivalentes.\n- Comprender props, estados, composición y limitaciones técnicas.",
    "ejemplo": "- Mapear un componente de diseño a código.\n- Identificar gaps, adaptaciones necesarias y decisiones que deben negociarse.",
    "indice": ""
  },
  {
    "id": "s83",
    "bloque": "6. Tecnología para diseñadores",
    "tipo": "Sesión de contenido",
    "titulo": "Elaboración de prompts para diseño",
    "profesor": "Manu Lorenzo",
    "comunicada": "2027-03-03",
    "confirmada": "2027-03-03",
    "objetivos": "Principal: Formular instrucciones que incluyan contexto, restricciones, criterios y formato de salida, y mejorar el resultado mediante evaluación iterativa.\n- Comprender la estructura de un prompt útil para diseño.\n- Distinguir especificación, referencia, restricción y criterio de calidad.",
    "ejemplo": "- Iterar un prompt ineficaz hasta obtener un resultado usable.\n- Documentar qué cambios mejoraron el resultado y qué no pudo resolverse con prompting.",
    "indice": ""
  },
  {
    "id": "s84",
    "bloque": "6. Tecnología para diseñadores",
    "tipo": "Skills",
    "titulo": "DECÍDETE: ADAPTABILIDAD Y PENSAMIENTO CRÍTICO",
    "profesor": "Juan Portillo",
    "comunicada": "2027-03-04",
    "confirmada": "2027-03-04",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s85",
    "bloque": "6. Tecnología para diseñadores",
    "tipo": "Sesión de contenido",
    "titulo": "Proceso de trabajo con Figma y herramientas complementarias",
    "profesor": "Adrià Linares",
    "comunicada": "2027-03-08",
    "confirmada": "2027-03-08",
    "objetivos": "Principal: Diseñar un flujo conectado que reduzca duplicidades y preserve trazabilidad entre diseño, validación, documentación e implementación e iteración.\n- Conocer integraciones y automatizaciones relevantes.\n- Comprender riesgos de pérdida de versión, contexto y propiedad de la información.",
    "ejemplo": "- Representar y ejecutar un workflow real.\n- Evaluar entradas, salidas, responsables, controles de calidad y puntos de fallo.",
    "indice": ""
  },
  {
    "id": "s86",
    "bloque": "6. Tecnología para diseñadores",
    "tipo": "Sesión de contenido",
    "titulo": "Handoff a equipo completo",
    "profesor": "Pepe García",
    "comunicada": "2027-03-09",
    "confirmada": "2027-03-09",
    "objetivos": "Principal: Entregar una solución suficientemente definida para que pueda implementarse sin decisiones críticas no resueltas.\n- Comprender qué información necesitan desarrollo, producto y QA.\n- Conocer criterios de especificación, assets, estados y aceptación.",
    "ejemplo": "- Preparar un handoff completo.\n- Realizar una sesión de traspaso y recoger ambigüedades o gaps detectados por el equipo.",
    "indice": ""
  },
  {
    "id": "s87",
    "bloque": "6. Tecnología para diseñadores",
    "tipo": "Sesión de contenido",
    "titulo": "Fundamentos técnicos para trabajar con developers (cómo entender modelos, prompts, integraciones.)",
    "profesor": "Adrià Linares",
    "comunicada": "2027-03-10",
    "confirmada": "2027-03-10",
    "objetivos": "Principal: Anticipar cómo datos, APIs, estados y restricciones técnicas condicionan una solución de diseño.\n- Comprender de forma funcional frontend, backend, API, base de datos y autenticación.\n- Conocer estados y dependencias habituales.",
    "ejemplo": "- Revisar técnicamente una propuesta.\n- Documentar datos necesarios, estados, riesgos y preguntas que deben resolverse con desarrollo.",
    "indice": ""
  },
  {
    "id": "s88",
    "bloque": "6. Tecnología para diseñadores",
    "tipo": "Skills",
    "titulo": "TALLER COMUNICACIÓN",
    "profesor": "Toni Cantó",
    "comunicada": "2027-03-11",
    "confirmada": "2027-03-11",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s89",
    "bloque": "6. Tecnología para diseñadores",
    "tipo": "Sesión de contenido",
    "titulo": "Introducción a diseño de agentes como soluciones innovadoras. (I)",
    "profesor": "Germán Enguix",
    "comunicada": "2027-03-22",
    "confirmada": "2027-03-22",
    "objetivos": "Principal: Comprender qué es un agente de IA, cómo funciona y en qué tipos de tareas o problemas puede aportar valor dentro de un producto, servicio o proceso de trabajo.\n- Diferenciar un agente de IA de un chatbot, un asistente conversacional y una automatización tradicional.\n- Comprender sus elementos básicos: objetivo, contexto, memoria, herramientas, acciones y supervisión.\n- Identificar en qué tipos de problemas aporta valor y cuándo conviene utilizar otra solución.",
    "ejemplo": "- Analizar ejemplos reales o simulados de chatbots, asistentes, automatizaciones y agentes, identificando sus diferencias.\n- Descomponer el funcionamiento de un agente en:objetivo;información que recibe;decisiones que toma;herramientas que utiliza;acciones que ejecuta;resultado que entrega;supervisión que necesita.\n- Clasificar varios problemas de producto según convenga resolverlos con:una interfaz;una automatización;un asistente;un agente.\n- Seleccionar un caso de uso y justificar qué valor aportaría el agente frente a una solución convencional.",
    "indice": ""
  },
  {
    "id": "s90",
    "bloque": "6. Tecnología para diseñadores",
    "tipo": "Sesión de contenido",
    "titulo": "Introducción a diseño de agentes como soluciones innovadoras. (II)",
    "profesor": "Germán Enguix",
    "comunicada": "2027-03-23",
    "confirmada": "2027-03-23",
    "objetivos": "Principal: Diseñar y utilizar un agente sencillo para resolver una tarea concreta, definiendo su comportamiento, herramientas, límites y mecanismos de supervisión.\n- Traducir una necesidad de usuario o negocio en un objetivo y unas instrucciones claras para el agente.\n- Definir su autonomía, herramientas, memoria, límites y puntos de supervisión humana.\n- Probar e iterar el agente mediante distintos escenarios, evaluando utilidad, precisión, control y seguridad.",
    "ejemplo": "- Diseñar un agente para un caso concreto del máster, por ejemplo:\n- investigar tendencias y sintetizar fuentes; preparar una entrevista de research; analizar feedback de usuarios; revisar accesibilidad; ayudar a mantener un sistema de diseño; preparar información para un stakeholder. - Probarlo y Evaluar sus resultados mediante criterios de utilidad, precisión, autonomía, transparencia, control y seguridad.\n- Iterar sus instrucciones o funcionamiento a partir de los fallos detectados.",
    "indice": ""
  },
  {
    "id": "s91",
    "bloque": "6. Tecnología para diseñadores",
    "tipo": "Proyecto MUX",
    "titulo": "PUNTO CONTROL SPRINT STARTUP PROJECT  (estrategia + problema cerrado)",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "",
    "confirmada": "",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s92",
    "bloque": "6. Tecnología para diseñadores",
    "tipo": "Proyecto MUX",
    "titulo": "Punto control Individual + requisitos",
    "profesor": "Paula Girela González",
    "comunicada": "2027-03-24",
    "confirmada": "2027-03-24",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s93",
    "bloque": "6. Tecnología para diseñadores",
    "tipo": "Sesión de contenido",
    "titulo": "DesignOps: Gestión y escalado inteligente con metodologías ágiles (I)",
    "profesor": "Yanina Wax",
    "comunicada": "2027-04-06",
    "confirmada": "2027-04-06",
    "objetivos": "Principal: Integrar el trabajo de diseño dentro del proceso de desarrollo de producto, coordinando decisiones, dependencias y entregables\n- Comprender cómo se relacionan diseño, producto y tecnología dentro de un ciclo ágil de trabajo.\n- Identificar dependencias, riesgos técnicos y momentos de coordinación necesarios antes, durante y después del desarrollo.\n- Organizar el trabajo de diseño para que llegue al equipo técnico con el nivel de definición adecuado y pueda evolucionar durante la implementación.",
    "ejemplo": "- Diseñar el flujo de trabajo de una funcionalidad desde su definición hasta su puesta en producción.\n- Detectar posibles bloqueos, retrabajos o pérdidas de información y proponer mejoras operativas.",
    "indice": ""
  },
  {
    "id": "s94",
    "bloque": "6. Tecnología para diseñadores",
    "tipo": "Sesión de contenido",
    "titulo": "DesignOps: Gestión y escalado inteligente con metodologías ágiles (II)",
    "profesor": "Yanina Wax",
    "comunicada": "2027-04-07",
    "confirmada": "2027-04-07",
    "objetivos": "Principal: Escalado, gobernanza y mejora continua del producto\n- Comprender cómo establecer mecanismos de gobernanza para mantener la consistencia del diseño cuando aumentan los equipos, productos o contribuyentes.\n- Definir procesos de contribución, revisión, documentación y actualización de componentes y patrones.\n- Identificar métricas operativas para evaluar la eficiencia del sistema de diseño, la reducción de retrabajo y la adopción por parte de diseño y desarrollo.",
    "ejemplo": "- Crear una Definition of Done de diseño y de producto\n- Aplicarla a una tarea y detectar qué impide considerarla terminada.",
    "indice": ""
  },
  {
    "id": "s95",
    "bloque": "6. Tecnología para diseñadores",
    "tipo": "Institucional / calendario",
    "titulo": "Excursión Albalat",
    "profesor": "Paula Girela González",
    "comunicada": "",
    "confirmada": "",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s96",
    "bloque": "7. Ciclo de vida, lanzamiento y gestión de producto digital",
    "tipo": "Sesión de contenido",
    "titulo": "Ciclo de vida del producto",
    "profesor": "Adrián Martín",
    "comunicada": "2027-04-12",
    "confirmada": "2027-04-12",
    "objetivos": "Principal: Adaptar las prioridades de diseño y producto a la etapa de evolución de una solución.\n- Conocer características de lanzamiento, crecimiento, madurez y declive.\n- Comprender cómo cambian objetivos, riesgos y métricas.",
    "ejemplo": "- Diagnosticar la fase de un producto real.\n- Proponer prioridades de diseño coherentes y justificar qué no debería priorizarse.",
    "indice": ""
  },
  {
    "id": "s97",
    "bloque": "7. Ciclo de vida, lanzamiento y gestión de producto digital",
    "tipo": "Sesión de contenido",
    "titulo": "Herramientas para el Ciclo de vida del producto",
    "profesor": "Adrián Martín",
    "comunicada": "2027-04-13",
    "confirmada": "2027-04-13",
    "objetivos": "Principal: Seleccionar métricas, fuentes y herramientas de seguimiento adecuadas a la fase y a la decisión que se necesita tomar.\n- Conocer categorías de herramientas de analítica (solo recordarlas, pq ya las han visto en temas previos), feedback y experimentación.\n- Comprender el impacto de un proceso iterativo.",
    "ejemplo": "- Elaborar un plan de medición.\n- Definir pregunta, métrica, fuente, herramienta, frecuencia, responsable y decisión asociada.",
    "indice": ""
  },
  {
    "id": "s98",
    "bloque": "7. Ciclo de vida, lanzamiento y gestión de producto digital",
    "tipo": "Sesión de contenido",
    "titulo": "Go to Market & Pricing",
    "profesor": "Rosa Horcajada",
    "comunicada": "2027-04-14",
    "confirmada": "2027-04-14",
    "objetivos": "Principal: Conectar propuesta de valor, segmento, posicionamiento y modelo de precio en una estrategia de lanzamiento coherente.\n- Comprender fundamentos de segmentación, posicionamiento, canales y pricing.\n- Distinguir precio, modelo de ingresos y disposición a pagar.",
    "ejemplo": "- Crear una propuesta de lanzamiento.\n- Incluir audiencia, mensaje, canal, hipótesis de precio y plan de validación.",
    "indice": ""
  },
  {
    "id": "s99",
    "bloque": "7. Ciclo de vida, lanzamiento y gestión de producto digital",
    "tipo": "Pendiente de definir",
    "titulo": "Sin título (pendiente de definir)",
    "profesor": "",
    "comunicada": "",
    "confirmada": "",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s100",
    "bloque": "7. Ciclo de vida, lanzamiento y gestión de producto digital",
    "tipo": "Proyecto MUX",
    "titulo": "JORNADA DE TRABAJO STARTUP PROJECT",
    "profesor": "",
    "comunicada": "",
    "confirmada": "",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s101",
    "bloque": "7. Ciclo de vida, lanzamiento y gestión de producto digital",
    "tipo": "Sesión de contenido",
    "titulo": "Product Discovery vs Delivery (priorización)(I)",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "2027-04-20",
    "confirmada": "2027-04-20",
    "objetivos": "Principal: Distinguir incertidumbres que deben investigarse de soluciones suficientemente definidas para entrar en delivery.\n- Comprender riesgos de valor, usabilidad, viabilidad y factibilidad.\n- Conocer actividades de discovery y su relación con delivery. (Y Dual TRack)",
    "ejemplo": "- Elaborar un mapa de priorización y riesgos para una iniciativa.\n- Seleccionar actividades de discovery proporcionadas a cada incertidumbre.",
    "indice": ""
  },
  {
    "id": "s102",
    "bloque": "7. Ciclo de vida, lanzamiento y gestión de producto digital",
    "tipo": "Sesión de contenido",
    "titulo": "Product Discovery vs Delivery (priorización)(I)",
    "profesor": "Josep Martínez",
    "comunicada": "2027-04-20",
    "confirmada": "2027-04-20",
    "objetivos": "Principal: Distinguir incertidumbres que deben investigarse de soluciones suficientemente definidas para entrar en delivery.\n- Comprender riesgos de valor, usabilidad, viabilidad y factibilidad.\n- Conocer actividades de discovery y su relación con delivery. (Y Dual TRack)",
    "ejemplo": "- Elaborar un mapa de priorización y riesgos para una iniciativa.\n- Seleccionar actividades de discovery proporcionadas a cada incertidumbre.",
    "indice": ""
  },
  {
    "id": "s103",
    "bloque": "7. Ciclo de vida, lanzamiento y gestión de producto digital",
    "tipo": "Sesión de contenido",
    "titulo": "Product Discovery vs Delivery (RICE, Kano, MoSCoW, Opportunity Solution Tree, TARS)(II)",
    "profesor": "Pau Amat",
    "comunicada": "2027-04-21",
    "confirmada": "2027-04-21",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s104",
    "bloque": "7. Ciclo de vida, lanzamiento y gestión de producto digital",
    "tipo": "Proyecto MUX",
    "titulo": "PUNTO CONTROL SPRINT STARTUP PROJECT (idea journey TO BE)",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "",
    "confirmada": "",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s105",
    "bloque": "7. Ciclo de vida, lanzamiento y gestión de producto digital",
    "tipo": "Coordinación",
    "titulo": "DINÁMICA COORDINACIÓN",
    "profesor": "Paula Girela González",
    "comunicada": "2027-04-22",
    "confirmada": "2027-04-22",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s106",
    "bloque": "7. Ciclo de vida, lanzamiento y gestión de producto digital",
    "tipo": "Sesión de contenido",
    "titulo": "Ciclo de vida del producto por predicción de uso, análisis de cohortes con IA.(I)",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "2027-04-26",
    "confirmada": "2027-04-26",
    "objetivos": "Principal: Interpretar un análisis de cohortes para localizar diferencias relevantes en activación, uso y retención.\n- Comprender cohorte, retención, abandono y comparación temporal.\n- Reconocer patrones y errores habituales de lectura.",
    "ejemplo": "- Analizar cohortes de un caso.\n- Formular hipótesis explicativas y señalar qué datos adicionales serían necesarios.",
    "indice": ""
  },
  {
    "id": "s107",
    "bloque": "7. Ciclo de vida, lanzamiento y gestión de producto digital",
    "tipo": "Sesión de contenido",
    "titulo": "Ciclo de vida del producto por predicción de uso, análisis de cohortes con IA.(II)",
    "profesor": "Lucía Gastelum",
    "comunicada": "2027-04-27",
    "confirmada": "",
    "objetivos": "Principal: Evaluar críticamente una predicción generada con IA distinguiendo evidencia, inferencia, incertidumbre y decisión.\n- Comprender límites de las predicciones basadas en datos insuficientes.\n- Reconocer sesgo, sobreajuste y falsa precisión.",
    "ejemplo": "- Revisar una predicción con sus supuestos y datos.\n- Recomendar su uso, revisión o rechazo y definir cómo validarla.",
    "indice": ""
  },
  {
    "id": "s108",
    "bloque": "7. Ciclo de vida, lanzamiento y gestión de producto digital",
    "tipo": "Sesión de contenido",
    "titulo": "Ejemplo práctico Design Sprint + A/B testing (con claude code??)",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "2027-04-28",
    "confirmada": "2027-04-28",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s109",
    "bloque": "7. Ciclo de vida, lanzamiento y gestión de producto digital",
    "tipo": "Sesión de contenido",
    "titulo": "Diseño con impacto en negocio (Métricas y frameworks de producto)(I)",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "2027-04-29",
    "confirmada": "2027-04-29",
    "objetivos": "Principal: Relacionar decisiones de diseño con comportamientos de usuario y métricas de producto para evaluar su impacto\n- Comprender la diferencia entre métricas de actividad, comportamiento, producto y negocio.\n- Conocer frameworks básicos de producto para ordenar métricas y detectar qué parte de la experiencia necesita mejora.\n- Identificar qué métricas pueden verse afectadas por una decisión de diseño y qué límites existen para atribuirle causalidad.",
    "ejemplo": "- Analizar un caso de producto e identificar su objetivo principal.\n- Construir un mapa que conecte:\n- decisión de diseño;comportamiento esperado;métrica de producto;\n- posible impacto en negocio.Seleccionar un framework adecuado para interpretar el caso, por ejemplo:AARRR;\n- HEART;funnel de conversión; NSM y métricas de apoyo.\n- Proponer qué datos deberían medirse antes y después de implementar una mejora.",
    "indice": ""
  },
  {
    "id": "s110",
    "bloque": "7. Ciclo de vida, lanzamiento y gestión de producto digital",
    "tipo": "Sesión de contenido",
    "titulo": "Diseño con impacto en negocio (NRR, PLG, expansion revenue)(II)",
    "profesor": "Pau Amat",
    "comunicada": "2027-05-03",
    "confirmada": "2027-05-03",
    "objetivos": "Principal: Evaluar cómo la experiencia de producto puede contribuir a la retención, expansión de ingresos y crecimiento liderado por producto.\n- Comprender qué son NRR, expansion revenue y Product-Led Growth, y cómo se relacionan con retención, adopción y crecimiento.\n- Identificar momentos de la experiencia que pueden impulsar activación, uso recurrente, ampliación de plan o colaboración entre usuarios.\n- Analizar cuándo una mejora de diseño puede generar impacto económico y cuándo esa relación no puede demostrarse sin más evidencia.",
    "ejemplo": "- Analizar un producto digital con modelo recurrente o freemium.\n- Identificar oportunidades de diseño vinculadas a:\n- activación;adopción de funcionalidades;retención;upgrade;cross-sell o expansión de uso.\n- Formular una hipótesis de impacto que conecte:cambio de diseño;comportamiento esperado;métrica de producto;efecto potencial en NRR o expansion revenue.\n- Proponer una forma de validación y señalar los riesgos de diseñar únicamente para maximizar ingresos.",
    "indice": ""
  },
  {
    "id": "s111",
    "bloque": "7. Ciclo de vida, lanzamiento y gestión de producto digital",
    "tipo": "Sesión de contenido",
    "titulo": "Planificación, roadmaps, OKRs y trabajo con equipos ágiles(I)",
    "profesor": "Pau Amat",
    "comunicada": "2027-05-04",
    "confirmada": "2027-05-04",
    "objetivos": "Principal: Formular objetivos y resultados clave que expresen cambios relevantes, no listas de tareas o entregables.\n- Comprender diferencia entre objetivo, resultado, iniciativa y métrica.\n- Reconocer errores frecuentes en OKR.",
    "ejemplo": "- Redactar un OKR de producto o diseño.\n- Revisarlo para comprobar alineación, medición y capacidad de influencia.",
    "indice": ""
  },
  {
    "id": "s112",
    "bloque": "7. Ciclo de vida, lanzamiento y gestión de producto digital",
    "tipo": "Sesión de contenido",
    "titulo": "Planificación, roadmaps, OKRs y trabajo con equipos ágiles: Jira y Notion (II)",
    "profesor": "Guillermo Jávega",
    "comunicada": "2027-05-05",
    "confirmada": "2027-05-05",
    "objetivos": "Principal: Construir un roadmap orientado a resultados y capaz de adaptarse al aprendizaje y a la incertidumbre.\n- Comprender diferencias entre roadmap de funcionalidades y de resultados.\n- Conocer criterios de priorización, dependencias y revisión.",
    "ejemplo": "- Crear un roadmap con oportunidades, resultados y horizontes.\n- Definir condiciones para revisar o cambiar prioridades.",
    "indice": ""
  },
  {
    "id": "s113",
    "bloque": "7. Ciclo de vida, lanzamiento y gestión de producto digital",
    "tipo": "Proyecto MUX",
    "titulo": "JORNADA DE TRABAJO STARTUP PROJECT",
    "profesor": "",
    "comunicada": "",
    "confirmada": "",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s114",
    "bloque": "7. Ciclo de vida, lanzamiento y gestión de producto digital",
    "tipo": "Institucional / calendario",
    "titulo": "EI - EXPERIENCIA INTERNACIONAL",
    "profesor": "Paula Girela González",
    "comunicada": "2027-05-10",
    "confirmada": "2027-05-10",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s115",
    "bloque": "7. Ciclo de vida, lanzamiento y gestión de producto digital",
    "tipo": "Institucional / calendario",
    "titulo": "EI - EXPERIENCIA INTERNACIONAL",
    "profesor": "Paula Girela González",
    "comunicada": "2027-05-11",
    "confirmada": "2027-05-11",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s116",
    "bloque": "7. Ciclo de vida, lanzamiento y gestión de producto digital",
    "tipo": "Institucional / calendario",
    "titulo": "EI - EXPERIENCIA INTERNACIONAL",
    "profesor": "Paula Girela González",
    "comunicada": "2027-05-12",
    "confirmada": "2027-05-12",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s117",
    "bloque": "7. Ciclo de vida, lanzamiento y gestión de producto digital",
    "tipo": "Institucional / calendario",
    "titulo": "EI - EXPERIENCIA INTERNACIONAL",
    "profesor": "Paula Girela González",
    "comunicada": "2027-05-13",
    "confirmada": "2027-05-13",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s118",
    "bloque": "8. Liderazgo, negocio e impacto",
    "tipo": "Proyecto MUX",
    "titulo": "JORNADA DE TRABAJO STARTUP PROJECT + Presentaciones aprendizajes EI",
    "profesor": "",
    "comunicada": "",
    "confirmada": "",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s119",
    "bloque": "8. Liderazgo, negocio e impacto",
    "tipo": "Skills",
    "titulo": "TRANSFÓRMATE: GESTIÓN DE EQUIPOS Y LIDERAZGO",
    "profesor": "Juan Portillo",
    "comunicada": "2027-05-18",
    "confirmada": "",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s120",
    "bloque": "8. Liderazgo, negocio e impacto",
    "tipo": "Sesión de contenido",
    "titulo": "Liderazgo en equipos de producto y diseño",
    "profesor": "Lucía Gastelum",
    "comunicada": "2027-05-19",
    "confirmada": "",
    "objetivos": "Principal: Gestionar feedback y conflicto entre disciplinas manteniendo exigencia, respeto y orientación al resultado común.\n- Comprender causas frecuentes de conflicto entre diseño, producto y tecnología.\n- Conocer técnicas de feedback, mediación y acuerdos.",
    "ejemplo": "- Resolver un conflicto simulado.\n- Documentar posiciones, intereses, acuerdos, responsabilidades y siguientes pasos.",
    "indice": ""
  },
  {
    "id": "s121",
    "bloque": "8. Liderazgo, negocio e impacto",
    "tipo": "Sesión de contenido",
    "titulo": "Procesos empresariales",
    "profesor": "María Molinero",
    "comunicada": "2027-05-20",
    "confirmada": "",
    "objetivos": "Principal: Evaluar cómo una decisión de diseño afecta a operaciones, tecnología, comercial, soporte y otras áreas.\n- Comprender interdependencias entre experiencia y procesos internos.\n- Reconocer costes ocultos, cambios operativos y riesgos organizativos.",
    "ejemplo": "- Elaborar un mapa de impacto interdepartamental.\n- Identificar actores, dependencias, beneficios, costes y condiciones de implantación.",
    "indice": ""
  },
  {
    "id": "s122",
    "bloque": "8. Liderazgo, negocio e impacto",
    "tipo": "Proyecto MUX",
    "titulo": "ENTREGA SPRINT STARTUP PROJECT (Interfaz/solucion)",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "",
    "confirmada": "",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s123",
    "bloque": "8. Liderazgo, negocio e impacto",
    "tipo": "Sesión de contenido",
    "titulo": "Decisiones basadas en datos - Dashboard",
    "profesor": "Rebeca Zaragozá",
    "comunicada": "2027-05-25",
    "confirmada": "2027-05-25",
    "objetivos": "Principal: Interpretar un dashboard distinguiendo señal, anomalía y contexto antes de formular una hipótesis de diseño.\n- Comprender métricas, tendencias, segmentos y comparaciones.\n- Reconocer errores de causalidad, agregación y lectura aislada.",
    "ejemplo": "- Analizar un dashboard.\n- Formular preguntas, hipótesis y necesidades de evidencia adicional antes de recomendar cambios.",
    "indice": ""
  },
  {
    "id": "s124",
    "bloque": "8. Liderazgo, negocio e impacto",
    "tipo": "Sesión de contenido",
    "titulo": "Decisiones basadas en datos (Test A/B y CRO)",
    "profesor": "Pablo de la Fuente",
    "comunicada": "2027-05-26",
    "confirmada": "2027-05-26",
    "objetivos": "Principal: Diseñar una intervención de optimización conectada con una fricción del funnel y una métrica de conversión.\n- Comprender funnel, conversión, microconversión y métricas de control (Han visto Journeys. Han mencionado CRO con behavioral).\n- Distinguir optimización de manipulación y mejora local de impacto global.",
    "ejemplo": "- Diseñar un experimento CRO.\n- Definir diagnóstico, hipótesis, cambio, métrica principal, métricas de protección y regla de decisión.",
    "indice": ""
  },
  {
    "id": "s125",
    "bloque": "8. Liderazgo, negocio e impacto",
    "tipo": "Institucional / calendario",
    "titulo": "Visita Colmena",
    "profesor": "Paula Girela González",
    "comunicada": "",
    "confirmada": "",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s126",
    "bloque": "8. Liderazgo, negocio e impacto",
    "tipo": "Sesión de contenido",
    "titulo": "Stakeholder management y argumentación de diseño: Aprovechamiento de la IA para preparar presentaciones, dashboards, resúmenes ejecutivos.(I)",
    "profesor": "Lucía Gastelum",
    "comunicada": "2027-05-31",
    "confirmada": "",
    "objetivos": "Principal: Seleccionar y estructurar la información necesaria para facilitar una decisión ejecutiva (research, behavioral, basado en datos...).\n- Comprender intereses, poder, influencia y necesidades de información de los stakeholders.\n- Conocer estructuras de narrativa ejecutiva.",
    "ejemplo": "- Crear una presentación con contexto, evidencia, alternativas, recomendación, riesgos y petición concreta.\n- Validar que cada dato aporta a la decisión.",
    "indice": ""
  },
  {
    "id": "s127",
    "bloque": "8. Liderazgo, negocio e impacto",
    "tipo": "Sesión de contenido",
    "titulo": "Stakeholder management y argumentación de diseño: Aprovechamiento de la IA para preparar presentaciones, dashboards, resúmenes ejecutivos.(II)",
    "profesor": "Lucía Gastelum",
    "comunicada": "2027-06-01",
    "confirmada": "",
    "objetivos": "Principal: Utilizar IA para adaptar una comunicación a distintos stakeholders sin alterar, inventar ni simplificar indebidamente la evidencia.\n- Comprender riesgos de generación, resumen y visualización automática.\n- Distinguir adaptación del mensaje de distorsión del contenido.",
    "ejemplo": "- Crear versiones para dirección, producto y tecnología.\n- Verificarlas contra las fuentes y documentar cambios de enfoque, no de hechos.",
    "indice": ""
  },
  {
    "id": "s128",
    "bloque": "8. Liderazgo, negocio e impacto",
    "tipo": "Sesión de contenido",
    "titulo": "Dinámicas de trabajo con Product Managers y equipos de desarrollo",
    "profesor": "Pau Amat",
    "comunicada": "2027-06-02",
    "confirmada": "2027-06-02",
    "objetivos": "Principal: Negociar el alcance de una solución equilibrando valor para el usuario, impacto de negocio, restricciones y esfuerzo técnico.\n- Comprender responsabilidades y tensiones entre diseño, PM y desarrollo.\n- Conocer técnicas de negociación basada en intereses y trade-offs.",
    "ejemplo": "- Simular una negociación de alcance.\n- Documentar acuerdos, renuncias, riesgos, criterios y aspectos diferidos.",
    "indice": ""
  },
  {
    "id": "s129",
    "bloque": "8. Liderazgo, negocio e impacto",
    "tipo": "Sesión de contenido",
    "titulo": "Design critiques",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "2027-06-03",
    "confirmada": "2027-06-03",
    "objetivos": "Principal: Dar y recibir crítica de diseño basada en objetivos, evidencia y principios, evitando preferencias personales sin fundamento.\n- Comprender finalidad, reglas y estructura de una critique.\n- Distinguir observación, interpretación, juicio y recomendación.",
    "ejemplo": "- Participar en una critique estructurada.\n- Documentar fortalezas, problemas, preguntas y recomendaciones priorizadas.",
    "indice": ""
  },
  {
    "id": "s130",
    "bloque": "8. Liderazgo, negocio e impacto",
    "tipo": "Sesión de contenido",
    "titulo": "Comunicación oral y escrita en entrevistas",
    "profesor": "MaríaCantó Pérez",
    "comunicada": "2027-06-07",
    "confirmada": "2027-06-07",
    "objetivos": "Principal: Comunicar experiencias y decisiones profesionales de manera estructurada, concreta y creíble.\n- Comprender qué busca evaluar una pregunta de entrevista.\n- Conocer estructuras como STAR y adaptación oral/escrita.",
    "ejemplo": "- Preparar respuestas a preguntas técnicas y conductuales.\n- Recibir evaluación sobre claridad, relevancia, evidencia, rol y aprendizaje.",
    "indice": ""
  },
  {
    "id": "s131",
    "bloque": "8. Liderazgo, negocio e impacto",
    "tipo": "Sesión de contenido",
    "titulo": "Procesos de selección para diseñadores",
    "profesor": "Malena Sanchís",
    "comunicada": "2027-06-08",
    "confirmada": "2027-06-08",
    "objetivos": "Principal: Adaptar la candidatura a los criterios que se evalúan en cada etapa de un proceso de selección.\n- Conocer fases habituales: candidatura, portfolio, screening, prueba y entrevista.\n- Comprender qué evidencia espera cada interlocutor.",
    "ejemplo": "- Elaborar un plan de preparación por fase.\n- Definir mensaje, pruebas, preguntas, riesgos y errores que deben evitarse.",
    "indice": ""
  },
  {
    "id": "s132",
    "bloque": "8. Liderazgo, negocio e impacto",
    "tipo": "Sesión de contenido",
    "titulo": "Elaboración de portfolio",
    "profesor": "Carlos Velasco",
    "comunicada": "2027-06-09",
    "confirmada": "",
    "objetivos": "Principal: Construir casos de portfolio que demuestren capacidad para comprender problemas, tomar decisiones, validar soluciones y generar impacto.\n- Comprender qué diferencia un caso profesional de una descripción cronológica del proceso.\n- Conocer criterios de selección, narrativa y evidencia.",
    "ejemplo": "- Seleccionar dos o tres proyectos relevantes.\n- Redactar casos con contexto, problema, rol, evidencia, decisiones, solución, validación, resultados y aprendizajes.",
    "indice": ""
  },
  {
    "id": "s133",
    "bloque": "8. Liderazgo, negocio e impacto",
    "tipo": "Proyecto MUX",
    "titulo": "JORNADA DE TRABAJO STARTUP PROJECT",
    "profesor": "",
    "comunicada": "",
    "confirmada": "",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s134",
    "bloque": "8. Liderazgo, negocio e impacto",
    "tipo": "Proyecto MUX",
    "titulo": "DEFENSA PROYECTO INDIVIDUAL",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "2027-06-14",
    "confirmada": "2027-06-14",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s135",
    "bloque": "8. Liderazgo, negocio e impacto",
    "tipo": "Coordinación",
    "titulo": "DINÁMICA COORDINACIÓN FINAL",
    "profesor": "Paula Girela González",
    "comunicada": "2027-06-14",
    "confirmada": "2027-06-14",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  },
  {
    "id": "s136",
    "bloque": "8. Liderazgo, negocio e impacto",
    "tipo": "Institucional / calendario",
    "titulo": "TFM - DEFENSA STARTUP PROJECT",
    "profesor": "Miriam Sánchez Muñoz",
    "comunicada": "2027-07-01",
    "confirmada": "",
    "objetivos": "",
    "ejemplo": "",
    "indice": ""
  }
];
